### ISSUE TITLE
gave up, huh?

### ISSUE THREAD

**Issue by cdaringe** [hoodie/shell-uglify#1]
too bad! could have been GREAT! ;)

**Comment by hoodie** [comment]
I dont know what you mean, this script does exactly that

**Comment by cdaringe** [comment]
It's just a cp command.  What am I missing?

**Comment by hoodie** [comment]
This is mean to be a joke, don't use this thing :grin: 
The assumption is that shell code is ugly per se, so no need to uglify it even further.
I know, it'd be cool to have something that really compresses shell code, but this is not it.
