### ISSUE TITLE
failure on windows

### ISSUE THREAD

**Issue by nixinator** [hoodie/shell-uglify#2]
i can't get this awesome script to run on windows,

it says, cp not found.

and then deleted my hard drive....

i installed nixos instead..... and my problems went away.

what can i do to install windows again.

**Comment by DieracDelta** [comment]
I am also encountering this issue. The suggested fix worked. Thanks.

**Comment by devfbe** [comment]
Maybe installing internet explorer 6 helps.

**Comment by nixinator** [comment]
it said that i needed a license for internet explorer 6.... seems nixos is a clear winner.
